require("options")
require("plugins")
require("mappings")
require("themes.nord")
--require("themes.onenord")
--vim.cmd.colorscheme "nordfox"
--vim.cmd.colorscheme "kanagawa-dragon"
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.nvim-treesitter")
require("plugins.indent-blankline")
require("plugins.gitsigns")
require("plugins.autopairs")
require("plugins.mini.move")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.symbols-outline")
require("plugins.golang")
